trigger:
- main

variables:
  githubRegistry: 'ghcr.io'
  imageName: 'nodejs-app'
  imageTag: 'latest'

stages:
- stage: Build_and_Push_Image
  displayName: 'Build and Push Docker Image to GHCR'
  jobs:
  - job: Build
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: 'My_Pool'
    steps:
    - task: Docker@2
      displayName: 'Login to GitHub Container Registry'
      inputs:
        command: login
        containerRegistry: 'Git_Docker_Registry'  # Reference your Service Connection here

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        repository: $(githubRegistry)/<your-username>/$(imageName)
        tags: $(imageTag)

    - task: Docker@2
      displayName: 'Push Docker Image to GHCR'
      inputs:
        command: push
        repository: $(githubRegistry)/<your-username>/$(imageName)
        tags: $(imageTag)
